name: ESLint
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  eslint:
    strategy:
      matrix:
        package:
          - jekyll-theme-dummy-react
          - jekyll-theme-dummy-vue
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies for ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: npm install --no-optional --silent
      - name: Lint for ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: npm run eslint
      - name: Build for ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: npm run build
